### ISSUE TITLE
Adapter Crash when interacting with ui

### ISSUE THREAD

**Issue by asgothian** [ioBroker/ioBroker.lovelace#28]
I just installed the latest version of the Lovelace adapter, but cannot get it to run stable. I have a number of lamps assigned to rooms, and they do show up on the ui, but as soon as i try to change the state, the adapter crashes with the following log. 
```

2019-08-26 17:48:07.108 - error: Caught by controller[0]: TypeError: Cannot read property 'brightness_pct' of undefined
--
2019-08-26 17:48:07.108 - error: Caught by controller[0]: at Socket.adapter.setForeignState (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:1046:52)
2019-08-26 17:48:07.109 - error: Caught by controller[0]: at Socket.onack (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:312:9)
2019-08-26 17:48:07.109 - error: Caught by controller[0]: at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:236:12)
2019-08-26 17:48:07.109 - error: Caught by controller[0]: at Manager. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
2019-08-26 17:48:07.110 - error: Caught by controller[0]: at Manager.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
2019-08-26 17:48:07.110 - error: Caught by controller[0]: at Manager.ondecoded (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:332:8)
2019-08-26 17:48:07.110 - error: Caught by controller[0]: at Decoder. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
2019-08-26 17:48:07.110 - error: Caught by controller[0]: at Decoder.Emitter.emit (/opt/iobroker/node_modules/component-emitter/index.js:134:20)
2019-08-26 17:48:07.111 - error: Caught by controller[0]: at Decoder.add (/opt/iobroker/node_modules/socket.io-parser/index.js:246:12)
2019-08-26 17:48:07.111 - error: Caught by controller[0]: at Manager.ondata (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:322:16)
2019-08-26 17:48:07.111 - error: host.ioTinker instance system.adapter.lovelace.0 terminated with code 6 (uncaught exception)

```

Note - the lights i am trying to switch are using the deconz adapter.

My system is:
Asus Tinkerboard with Raspbian
Node 8.15
NPM 6.5.0
Admin 3.6.0
JS Controller 1.5.7

**Comment by asgothian** [comment]
Ok.. a bit of debugging later - data.data_servivce.brightness_pct looks very odd.. especially when it seems to be called data.service_data in all other locations.

Also matches the logged info from the adapter:
```
{"type":"call_service","domain":"light","service":"turn_on","service_data":{"entity_id":"light.Bedroom_Ceiling"},"id":21}
```
