### ISSUE TITLE
TypeError: cannot read property of '0'

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.lovelace#29]
directly after start the adapter don't work 

`2019-08-27 06:14:03.448  - info: iobroker upgrade lovelace
2019-08-27 06:14:04.529  - info: iobroker Update lovelace from @0.1.4 to @0.1.5
2019-08-27 06:14:05.139  - info: iobroker npm install iobroker.lovelace@0.1.5 --production --save --prefix "/opt/iobroker" (System call)
2019-08-27 06:14:35.203  - info: iobroker npm install --production (System call) in "/opt/iobroker/node_modules/iobroker.lovelace"
2019-08-27 06:15:33.611  - error: iobroker system.adapter.lovelace does not exist
2019-08-27 06:15:33.612  - info: iobroker got /opt/iobroker/node_modules/iobroker.lovelace/admin
2019-08-27 06:15:33.643  - info: iobroker upload [6] lovelace.admin /opt/iobroker/node_modules/iobroker.lovelace/admin/words.js words.js application/javascript
2019-08-27 06:15:33.717  - info: iobroker upload [5] lovelace.admin /opt/iobroker/node_modules/iobroker.lovelace/admin/tab_m.html tab_m.html text/html
2019-08-27 06:15:33.772  - info: iobroker upload [4] lovelace.admin /opt/iobroker/node_modules/iobroker.lovelace/admin/style.css style.css text/css
2019-08-27 06:15:33.841  - info: iobroker upload [3] lovelace.admin /opt/iobroker/node_modules/iobroker.lovelace/admin/lovelace.png lovelace.png image/png
2019-08-27 06:15:33.910  - info: iobroker upload [2] lovelace.admin /opt/iobroker/node_modules/iobroker.lovelace/admin/js-yaml.min.js js-yaml.min.js application/javascript
2019-08-27 06:15:33.988  - info: iobroker upload [1] lovelace.admin /opt/iobroker/node_modules/iobroker.lovelace/admin/index_m.html index_m.html text/html
2019-08-27 06:15:34.051  - info: iobroker upload [0] lovelace.admin /opt/iobroker/node_modules/iobroker.lovelace/admin/custom_m.html custom_m.html text/html
2019-08-27 06:15:34.107  - info: iobroker Adapter "lovelace" updated
2019-08-27 06:19:29.541  - info: iobroker upload lovelace
2019-08-27 06:19:29.884  - info: iobroker got /opt/iobroker/node_modules/iobroker.lovelace/admin
2019-08-27 06:19:29.911  - info: iobroker upload [6] lovelace.admin /opt/iobroker/node_modules/iobroker.lovelace/admin/words.js words.js application/javascript
2019-08-27 06:19:29.982  - info: iobroker upload [5] lovelace.admin /opt/iobroker/node_modules/iobroker.lovelace/admin/tab_m.html tab_m.html text/html
2019-08-27 06:19:30.046  - info: iobroker upload [4] lovelace.admin /opt/iobroker/node_modules/iobroker.lovelace/admin/style.css style.css text/css
2019-08-27 06:19:30.101  - info: iobroker upload [3] lovelace.admin /opt/iobroker/node_modules/iobroker.lovelace/admin/lovelace.png lovelace.png image/png
2019-08-27 06:19:30.169  - info: iobroker upload [2] lovelace.admin /opt/iobroker/node_modules/iobroker.lovelace/admin/js-yaml.min.js js-yaml.min.js application/javascript
2019-08-27 06:19:30.243  - info: iobroker upload [1] lovelace.admin /opt/iobroker/node_modules/iobroker.lovelace/admin/index_m.html index_m.html text/html
2019-08-27 06:19:30.303  - info: iobroker upload [0] lovelace.admin /opt/iobroker/node_modules/iobroker.lovelace/admin/custom_m.html custom_m.html text/html
2019-08-27 06:19:30.366  - error: iobroker system.adapter.lovelace does not exist
2019-08-27 06:19:36.483  - info: iobroker add lovelace  --host iobroker
2019-08-27 06:19:36.843  - info: iobroker host.iobroker install adapter lovelace
2019-08-27 06:19:36.855  - info: iobroker got /opt/iobroker/node_modules/iobroker.lovelace/admin
2019-08-27 06:19:36.880  - info: iobroker upload [6] lovelace.admin /opt/iobroker/node_modules/iobroker.lovelace/admin/words.js words.js application/javascript
2019-08-27 06:19:36.948  - info: iobroker upload [5] lovelace.admin /opt/iobroker/node_modules/iobroker.lovelace/admin/tab_m.html tab_m.html text/html
2019-08-27 06:19:37.005  - info: iobroker upload [4] lovelace.admin /opt/iobroker/node_modules/iobroker.lovelace/admin/style.css style.css text/css
2019-08-27 06:19:37.066  - info: iobroker upload [3] lovelace.admin /opt/iobroker/node_modules/iobroker.lovelace/admin/lovelace.png lovelace.png image/png
2019-08-27 06:19:37.136  - info: iobroker upload [2] lovelace.admin /opt/iobroker/node_modules/iobroker.lovelace/admin/js-yaml.min.js js-yaml.min.js application/javascript
2019-08-27 06:19:37.210  - info: iobroker upload [1] lovelace.admin /opt/iobroker/node_modules/iobroker.lovelace/admin/index_m.html index_m.html text/html
2019-08-27 06:19:37.277  - info: iobroker upload [0] lovelace.admin /opt/iobroker/node_modules/iobroker.lovelace/admin/custom_m.html custom_m.html text/html
2019-08-27 06:19:37.441  - info: iobroker host.iobroker object system.adapter.lovelace created
2019-08-27 06:19:37.467  - info: iobroker host.iobroker create instance lovelace
2019-08-27 06:19:37.488  - info: iobroker host.iobroker object lovelace.0.notifications.clear created
2019-08-27 06:19:37.517  - info: iobroker host.iobroker object lovelace.0.notifications.add created
2019-08-27 06:19:37.545  - info: iobroker host.iobroker object lovelace.0.notifications.list created
2019-08-27 06:19:37.573  - info: iobroker host.iobroker object lovelace.0.notifications created
2019-08-27 06:19:37.602  - info: iobroker host.iobroker object lovelace.0.control.alarm created
2019-08-27 06:19:37.630  - info: iobroker host.iobroker object lovelace.0.control.shopping_list created
2019-08-27 06:19:37.661  - info: iobroker host.iobroker object lovelace.0.control.data created
2019-08-27 06:19:37.689  - info: iobroker host.iobroker object lovelace.0.control.command created
2019-08-27 06:19:37.718  - info: iobroker host.iobroker object lovelace.0.control.instance created
2019-08-27 06:19:37.746  - info: iobroker host.iobroker object lovelace.0.control created
2019-08-27 06:19:37.775  - info: iobroker host.iobroker object lovelace.0.session created
2019-08-27 06:19:37.803  - info: iobroker host.iobroker object lovelace.0.configuration created
2019-08-27 06:19:37.833  - info: iobroker host.iobroker object lovelace.0 created
2019-08-27 06:19:37.861  - info: iobroker host.iobroker object lovelace.0.info.entitiesUpdated created
2019-08-27 06:19:37.890  - info: iobroker host.iobroker object lovelace.0.connected created
2019-08-27 06:19:37.921  - info: iobroker host.iobroker object lovelace.0.info created
2019-08-27 06:19:37.949  - info: iobroker host.iobroker object system.adapter.lovelace.0.outputCount created
2019-08-27 06:19:37.978  - info: iobroker host.iobroker object system.adapter.lovelace.0.inputCount created
2019-08-27 06:19:38.007  - info: iobroker host.iobroker object system.adapter.lovelace.0.uptime created
2019-08-27 06:19:38.036  - info: iobroker host.iobroker object system.adapter.lovelace.0.memRss created
2019-08-27 06:19:38.071  - info: iobroker host.iobroker object system.adapter.lovelace.0.memHeapTotal created
2019-08-27 06:19:38.116  - info: iobroker host.iobroker object system.adapter.lovelace.0.memHeapUsed created
2019-08-27 06:19:38.145  - info: iobroker host.iobroker object system.adapter.lovelace.0.cputime created
2019-08-27 06:19:38.183  - info: iobroker host.iobroker object system.adapter.lovelace.0.cpu created
2019-08-27 06:19:38.388  - info: iobroker host.iobroker object system.adapter.lovelace.0.connected created
2019-08-27 06:19:38.415  - info: iobroker host.iobroker object system.adapter.lovelace.0.alive created
2019-08-27 06:19:39.738  - info: host.iobroker object change system.adapter.lovelace.0
2019-08-27 06:19:39.757  - info: host.iobroker instance system.adapter.lovelace.0 started with pid 32100
2019-08-27 06:19:39.808  - info: iobroker host.iobroker object system.adapter.lovelace.0 created
2019-08-27 06:19:41.012  - info: lovelace.0 starting. Version 0.1.5 in /opt/iobroker/node_modules/iobroker.lovelace, node: v10.16.2
2019-08-27 06:19:41.043  - info: lovelace.0 http server listening on port 8091
2019-08-27 06:19:44.248  - error: lovelace.0 uncaught exception: Cannot read property '0' of undefined
2019-08-27 06:19:44.249  - error: lovelace.0 TypeError: Cannot read property '0' of undefined
    at WebServer._iobState2EntityState (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:1283:43)
    at ids.forEach (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:1609:90)
    at adapter.getForeignStates (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:1603:29)
2019-08-27 06:19:44.249  - info: lovelace.0 cleaned everything up...
2019-08-27 06:19:45.252  - info: lovelace.0 cleaned everything up...
2019-08-27 06:19:45.271  - error: Caught by controller[0]:     at WebServer._iobState2EntityState (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:1283:43)
2019-08-27 06:19:45.271  - error: Caught by controller[0]:     at ids.forEach (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:1609:90)
2019-08-27 06:19:45.271  - error: Caught by controller[0]:     at adapter.getForeignStates (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:1603:29)
2019-08-27 06:19:45.271  - error: host.iobroker instance system.adapter.lovelace.0 terminated with code 6 (uncaught exception)
2019-08-27 06:19:45.271  - info: host.iobroker Restart adapter system.adapter.lovelace.0 because enabled
2019-08-27 06:20:15.287  - info: host.iobroker instance system.adapter.lovelace.0 started with pid 439
2019-08-27 06:20:16.164  - info: lovelace.0 starting. Version 0.1.5 in /opt/iobroker/node_modules/iobroker.lovelace, node: v10.16.2
2019-08-27 06:20:16.195  - info: lovelace.0 http server listening on port 8091
2019-08-27 06:20:19.605  - error: lovelace.0 uncaught exception: Cannot read property '0' of undefined
2019-08-27 06:20:19.606  - error: lovelace.0 TypeError: Cannot read property '0' of undefined
    at WebServer._iobState2EntityState (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:1283:43)
    at ids.forEach (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:1609:90)
    at adapter.getForeignStates (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:1603:29)
2019-08-27 06:20:19.606  - info: lovelace.0 cleaned everything up...
2019-08-27 06:20:20.609  - info: lovelace.0 cleaned everything up...
2019-08-27 06:20:20.629  - error: Caught by controller[0]:     at WebServer._iobState2EntityState (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:1283:43)
2019-08-27 06:20:20.629  - error: Caught by controller[0]:     at ids.forEach (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:1609:90)
2019-08-27 06:20:20.629  - error: Caught by controller[0]:     at adapter.getForeignStates (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:1603:29)
2019-08-27 06:20:20.629  - error: host.iobroker instance system.adapter.lovelace.0 terminated with code 6 (uncaught exception)
2019-08-27 06:20:20.629  - info: host.iobroker Restart adapter system.adapter.lovelace.0 because enabled
2019-08-27 06:20:50.646  - info: host.iobroker instance system.adapter.lovelace.0 started with pid 1545
2019-08-27 06:20:51.462  - info: lovelace.0 starting. Version 0.1.5 in /opt/iobroker/node_modules/iobroker.lovelace, node: v10.16.2
2019-08-27 06:20:51.496  - info: lovelace.0 http server listening on port 8091
2019-08-27 06:20:54.327  - error: lovelace.0 uncaught exception: Cannot read property '0' of undefined
2019-08-27 06:20:54.327  - error: lovelace.0 TypeError: Cannot read property '0' of undefined
    at WebServer._iobState2EntityState (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:1283:43)
    at ids.forEach (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:1609:90)
    at adapter.getForeignStates (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:1603:29)
2019-08-27 06:20:54.328  - info: lovelace.0 cleaned everything up...
2019-08-27 06:20:55.330  - info: lovelace.0 cleaned everything up...
2019-08-27 06:20:55.389  - error: Caught by controller[0]:     at WebServer._iobState2EntityState (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:1283:43)
2019-08-27 06:20:55.389  - error: Caught by controller[0]:     at ids.forEach (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:1609:90)
2019-08-27 06:20:55.389  - error: Caught by controller[0]:     at adapter.getForeignStates (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:1603:29)
2019-08-27 06:20:55.389  - error: host.iobroker instance system.adapter.lovelace.0 terminated with code 6 (uncaught exception)
2019-08-27 06:20:55.389  - info: host.iobroker Restart adapter system.adapter.lovelace.0 because enabled
2019-08-27 06:20:58.979  - info: host.iobroker object change system.adapter.lovelace.0
2019-08-27 06:20:58.994  - info: host.iobroker instance system.adapter.lovelace.0 started with pid 1871
2019-08-27 06:20:59.833  - info: lovelace.0 starting. Version 0.1.5 in /opt/iobroker/node_modules/iobroker.lovelace, node: v10.16.2
2019-08-27 06:20:59.862  - info: lovelace.0 http server listening on port 8000
2019-08-27 06:21:02.885  - error: lovelace.0 uncaught exception: Cannot read property '0' of undefined
2019-08-27 06:21:02.885  - error: lovelace.0 TypeError: Cannot read property '0' of undefined
    at WebServer._iobState2EntityState (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:1283:43)
    at ids.forEach (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:1609:90)
    at adapter.getForeignStates (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:1603:29)
2019-08-27 06:21:02.886  - info: lovelace.0 cleaned everything up...
2019-08-27 06:21:03.889  - info: lovelace.0 cleaned everything up...
2019-08-27 06:21:03.911  - error: Caught by controller[0]:     at WebServer._iobState2EntityState (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:1283:43)
2019-08-27 06:21:03.911  - error: Caught by controller[0]:     at ids.forEach (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:1609:90)
2019-08-27 06:21:03.911  - error: Caught by controller[0]:     at adapter.getForeignStates (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:1603:29)
2019-08-27 06:21:03.912  - error: host.iobroker instance system.adapter.lovelace.0 terminated with code 6 (uncaught exception)
2019-08-27 06:21:03.912  - info: host.iobroker Restart adapter system.adapter.lovelace.0 because enabled
2019-08-27 06:21:27.784  - info: host.iobroker object change system.adapter.lovelace.0
2019-08-27 06:21:27.784  - info: host.iobroker "system.adapter.lovelace.0" disabled
2019-08-27 06:21:34.888  - error: lovelace.0 adapter disabled
2019-08-27 06:21:34.993  - error: host.iobroker instance system.adapter.lovelace.0 terminated with code 3 (Adapter disabled or invalid config)
2019-08-27 06:21:34.994  - info: host.iobroker Do not restart adapter system.adapter.lovelace.0 because disabled or deleted`

**Comment by Ilovegym66** [comment]
It's already in code tags..  but you're right, looks not easy to read. :-(

**Comment by Ilovegym66** [comment]
solved.
