### ISSUE TITLE
Lovelace startet nach Update über Github nicht mehr

### ISSUE THREAD

**Issue by nukleuz80** [ioBroker/ioBroker.lovelace#387]
Hi Garfonso,

ich habe gerade den Adapter über Github neu installiert und die Instanzen starten nicht mehr korrekt.

```
host.phoscon
2022-09-30 10:59:58.143	info	Restart adapter system.adapter.lovelace.0 because enabled
host.phoscon
2022-09-30 10:59:58.143	error	instance system.adapter.lovelace.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.phoscon
2022-09-30 10:59:58.143	error	Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
host.phoscon
2022-09-30 10:59:58.142	error	Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1085:14)
host.phoscon
2022-09-30 10:59:58.142	error	Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.lovelace/main.js:6:19)
host.phoscon
2022-09-30 10:59:58.142	error	Caught by controller[0]: at require (internal/modules/cjs/helpers.js:101:18)
host.phoscon
2022-09-30 10:59:58.142	error	Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:974:19)
host.phoscon
2022-09-30 10:59:58.142	error	Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:790:12)
host.phoscon
2022-09-30 10:59:58.142	error	Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:950:32)
host.phoscon
2022-09-30 10:59:58.141	error	Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
host.phoscon
2022-09-30 10:59:58.141	error	Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1085:14)
host.phoscon
2022-09-30 10:59:58.141	error	Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.lovelace/admin/words.js:10:18)
host.phoscon
2022-09-30 10:59:58.141	error	Caught by controller[0]: ReferenceError: systemDictionary is not defined
host.phoscon
2022-09-30 10:59:58.141	error	Caught by controller[0]: ^
host.phoscon
2022-09-30 10:59:58.141	error	Caught by controller[0]: systemDictionary = {
host.phoscon
2022-09-30 10:59:58.140	error	Caught by controller[0]: /opt/iobroker/node_modules/iobroker.lovelace/admin/words.js:10
```

Kannst du damit was anfangen?

Danke für Hilfe!

**Comment by Garfonso** [comment]
Ja, da hab ich was kaputt gemacht. :-/

Sollte jetzt wieder gehen. ;-)
