### ISSUE TITLE
Unknown request

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.lovelace#391]
**Describe the bug**  
When trying to control the air conditioner, the adapter went into a cyclic reboot.

**To Reproduce**  
1. Added my objects
2. Tried to control them
3. Got an adapter stop.

**Screenshots & Logfiles**  
<html>
<body>

2022-10-31 12:24:10.393 - warn: lovelace.0 (2790265) History instance is not selected in the settings
--
2022-10-31 12:24:10.396 - error: lovelace.0 (2790265) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-10-31 12:24:10.397 - error: lovelace.0 (2790265) unhandled promise rejection: result[i] is not iterable
2022-10-31 12:24:10.398 - error: lovelace.0 (2790265) TypeError: result[i] is not iterable
at convertHistoryResultToWebsocketApi (/opt/iobroker/node_modules/iobroker.lovelace/lib/modules/history.js:172:36)
at HistoryModule.processMessage (/opt/iobroker/node_modules/iobroker.lovelace/lib/modules/history.js:210:24)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-10-31 12:24:10.399 - error: lovelace.0 (2790265) result[i] is not iterable
2022-10-31 12:24:10.408 - info: lovelace.0 (2790265) cleaned everything up...
2022-10-31 12:24:10.411 - info: lovelace.0 (2790265) terminating
2022-10-31 12:24:10.412 - warn: lovelace.0 (2790265) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-10-31 12:24:11.070 - error: host.raspberrypi instance system.adapter.lovelace.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-10-31 12:24:11.072 - info: host.raspberrypi Restart adapter system.adapter.lovelace.0 because enabled
2022-10-31 12:24:41.218 - info: host.raspberrypi instance system.adapter.lovelace.0 started with pid 2794219
2022-10-31 12:24:44.531 - info: lovelace.0 (2794219) starting. Version 3.0.0 in /opt/iobroker/node_modules/iobroker.lovelace, node: v16.17.1, js-controller: 4.0.23
2022-10-31 12:24:44.641 - info: lovelace.0 (2794219) http server listening on port 8091
2022-10-31 12:24:54.595 - warn: lovelace.0 (2794219) History instance is not selected in the settings
2022-10-31 12:24:54.599 - error: lovelace.0 (2794219) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-10-31 12:24:54.600 - error: lovelace.0 (2794219) unhandled promise rejection: result[i] is not iterable
2022-10-31 12:24:54.601 - error: lovelace.0 (2794219) TypeError: result[i] is not iterable
at convertHistoryResultToWebsocketApi (/opt/iobroker/node_modules/iobroker.lovelace/lib/modules/history.js:172:36)
at HistoryModule.processMessage (/opt/iobroker/node_modules/iobroker.lovelace/lib/modules/history.js:210:24)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-10-31 12:24:54.602 - error: lovelace.0 (2794219) result[i] is not iterable
2022-10-31 12:24:54.614 - info: lovelace.0 (2794219) cleaned everything up...
2022-10-31 12:24:54.620 - info: lovelace.0 (2794219) terminating
2022-10-31 12:24:54.622 - warn: lovelace.0 (2794219) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-10-31 12:24:55.248 - error: host.raspberrypi Caught by controller[0]: Unknown request: {"type":"config/entity_registry/list","id":36}
2022-10-31 12:24:55.250 - error: host.raspberrypi Caught by controller[1]: Unknown request: {"type":"config/device_registry/list","id":37}
2022-10-31 12:24:55.251 - error: host.raspberrypi Caught by controller[2]: Unknown request: {"type":"config/area_registry/list","id":38}
2022-10-31 12:24:55.251 - error: host.raspberrypi instance system.adapter.lovelace.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-10-31 12:24:55.252 - info: host.raspberrypi Restart adapter system.adapter.lovelace.0 because enabled
2022-10-31 12:25:25.381 - info: host.raspberrypi instance system.adapter.lovelace.0 started with pid 2794427
2022-10-31 12:25:28.832 - info: lovelace.0 (2794427) starting. Version 3.0.0 in /opt/iobroker/node_modules/iobroker.lovelace, node: v16.17.1, js-controller: 4.0.23
2022-10-31 12:25:28.964 - info: lovelace.0 (2794427) http server listening on port 8091
2022-10-31 12:26:58.503 - warn: lovelace.0 (2794427) History instance is not selected in the settings
2022-10-31 12:26:58.511 - error: lovelace.0 (2794427) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-10-31 12:26:58.512 - error: lovelace.0 (2794427) unhandled promise rejection: result[i] is not iterable
2022-10-31 12:26:58.513 - error: lovelace.0 (2794427) TypeError: result[i] is not iterable
at convertHistoryResultToWebsocketApi (/opt/iobroker/node_modules/iobroker.lovelace/lib/modules/history.js:172:36)
at HistoryModule.processMessage (/opt/iobroker/node_modules/iobroker.lovelace/lib/modules/history.js:210:24)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-10-31 12:26:58.514 - error: lovelace.0 (2794427) result[i] is not iterable
2022-10-31 12:26:58.525 - info: lovelace.0 (2794427) cleaned everything up...
2022-10-31 12:26:58.529 - info: lovelace.0 (2794427) terminating
2022-10-31 12:26:58.531 - warn: lovelace.0 (2794427) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-10-31 12:26:59.138 - error: host.raspberrypi Caught by controller[0]: Unknown request: {"type":"config/entity_registry/list","id":12}
2022-10-31 12:26:59.139 - error: host.raspberrypi Caught by controller[1]: Unknown request: {"type":"config/device_registry/list","id":13}
2022-10-31 12:26:59.139 - error: host.raspberrypi Caught by controller[2]: Unknown request: {"type":"config/area_registry/list","id":14}
2022-10-31 12:26:59.140 - error: host.raspberrypi instance system.adapter.lovelace.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-10-31 12:26:59.140 - info: host.raspberrypi Restart adapter system.adapter.lovelace.0 because enabled
2022-10-31 12:26:59.140 - warn: host.raspberrypi Do not restart adapter system.adapter.lovelace.0 because restart loop detected

</body>
</html>

**Versions:**  
 - Adapter version: 3.0.0
 - JS-Controller version: 4.0.23
 - Node version: v16.17.1
 - Operating system: debian

**Comment by Anzic23** [comment]
I noticed that this happens after trying to see the history of the object in Lovelance

**Comment by Anzic23** [comment]
Found an error. It was necessary to select the history instance in the adapter settings.
![image](https://user-images.githubusercontent.com/37106885/198988146-0072159c-c256-4db4-a739-b9660380df45.png)

**Comment by Garfonso** [comment]
Yes... but not selecting a history instance should not crash the adapter (just not show history). So the report is valid. Thanks for noticing it. I'll try to fix it.
