### ISSUE TITLE
ioBroker App no longer opens Lovelace

### ISSUE THREAD

**Issue by Andiweli** [ioBroker/ioBroker.lovelace#486]
**Describe the bug**  

Installed Lovelace 4.1.1 today from 3.0.1 and now remote access via Smartphone app no longer is working.

iOS with latest ioBroker app from last week.

**Comment by Garfonso** [comment]
@GermanBluefox do we need to update something somewhere, when something in lovelace changes?
I still am not sure about how that works.

I got the pro-cloud working on my desktop once or so.. but it seems to be very unreliable for me for some time already... often the frontend get's stuck at "Loading Data" and retries over and over again without success. If it works, it usually works the first time... I tried to debug that, but did find a way to get information... so not sure where the issue could be.

**Comment by andiweli** [comment]
With the latest App updates, still no access from outside the WiFi is possible with Pro Account.

Tried an instance of iQontrol to cross-check if some config is wrong at my side - but iQontrol works.

**Comment by GermanBluefox** [comment]
Is it only app access to lovelace or the web access via iobroker.pro too?
I can access my lovelace via https://iobroker.pro/lovelace/ und über app.
![image](https://github.com/ioBroker/ioBroker.lovelace/assets/4582016/ff74f7bb-42f6-4be6-b0ba-940ecd8d472d)
![image](https://github.com/ioBroker/ioBroker.lovelace/assets/4582016/882074cf-dd4a-4139-a2fd-5f870c92cb78)

I cannot reproduce the problem

**Comment by andiweli** [comment]
Web Access via iobroker.pro never really worked for me.
App Access seems broken since a few updates.
Before I had to reload several times to get my Lovelace view loaded in the App.

iQontrol works. Via iobroker.pro and App.
The Lovelace config wasn't changed for months.

**Comment by andiweli** [comment]
Oh and of course Admin also works via iobroker.pro 😳

**Comment by GermanBluefox** [comment]
> Web Access via iobroker.pro never really worked for me.

so I suggest, that we solve first this problem as we can debug in Browser.

>App Access seems broken since a few updates.
It was nothing in the app concerning lovelace. But I restarted cloud.pro a coule days before and updated some vis packages

**Comment by andiweli** [comment]
All I get in Web (and App) is this... loads for ages. 

![image](https://github.com/ioBroker/ioBroker.lovelace/assets/11447150/ec0600fd-91c7-4c69-a294-15458868c36e)

**Comment by GermanBluefox** [comment]
> All I get in Web (and App) is this... loads for ages. From what I read the loading animation is a sign that a connection is established but the Lovelace adapter doesn't respond ... ?!
> 
> ![image](https://private-user-images.githubusercontent.com/11447150/308512224-ec0600fd-91c7-4c69-a294-15458868c36e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTYyOTcsIm5iZiI6MTcwOTExNTk5NywicGF0aCI6Ii8xMTQ0NzE1MC8zMDg1MTIyMjQtZWMwNjAwZmQtOTFjNy00YzY5LWEyOTQtMTU0NTg4NjhjMzZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDEwMjYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkYWU5ZjE0N2Y1ZThkN2QzMmNhMjdmMzdjOGFjZDQ4MmQ1NTljNmI4NjEyNDUxNmViMTNmN2E4OGM3MTM2YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ffpUKiZnG1cssDbNoP7pQ2NLaQeygsBKmCRNi3ZkW0Y)

What will be shown in browser console? And what in messages of socket communication?
![image](https://github.com/ioBroker/ioBroker.lovelace/assets/4582016/3db6fe96-34f1-4b34-913c-2ce054cabddc)

![image](https://github.com/ioBroker/ioBroker.lovelace/assets/4582016/4cfe9784-09fe-4121-a730-74fad17defa2)

**Comment by andiweli** [comment]
@GermanBluefox 

In browser console > network websockets > messages I get this when trying to connect to Lovelace via iobroker.pro...

`{type: "auth", access_token: "no_token"}
access_token
: 
"no_token"
type
: 
"auth"`


In Console I get this...

<img width="1427" alt="Bildschirmfoto 2024-02-28 um 18 58 42" src="https://github.com/ioBroker/ioBroker.lovelace/assets/11447150/9d2f1d69-3671-418e-b2a8-6dbc498013d6">

**Comment by GermanBluefox** [comment]
> `{type: "auth", access_token: "no_token"} access_token : "no_token" type : "auth"`

It is too few.... 
That what I have:
![image](https://github.com/ioBroker/ioBroker.lovelace/assets/4582016/007b6e1b-416f-4be6-bca3-fff1a29204c4)

**Comment by andiweli** [comment]
I'll take a look later when I am at home.

Funny thing... I just started the ioBroker Visu app out of couriosity on my iPhone and Lovelace loaded instantly!
I closed it and tried again and it didn't even showed the loading animation now...
Tried several times now but withotu success anymore :(

**Comment by andiweli** [comment]
@GermanBluefox as requested a new try... but that's all console shows me as in the screenshots.
iobroker.pro also doesn't load as mentioned... perhaps that's the reason there are no more messages shown.

<img width="1440" alt="Bildschirmfoto 2024-02-29 um 18 05 20" src="https://github.com/ioBroker/ioBroker.lovelace/assets/11447150/06305bcc-218a-4aed-8cad-c84e7d72c2b9">
<img width="1440" alt="Bildschirmfoto 2024-02-29 um 18 05 07" src="https://github.com/ioBroker/ioBroker.lovelace/assets/11447150/bfdfef31-4e55-4a52-86f0-2928d60345cc">

**Comment by andiweli** [comment]
@GermanBluefox ok after around 20-25 reload tries I got this and my Lovelace instance was shown via iobroker.pro

<img width="1440" alt="Bildschirmfoto 2024-02-29 um 18 17 25" src="https://github.com/ioBroker/ioBroker.lovelace/assets/11447150/72f4a2f3-4cd5-4b90-a7b7-94ebd864fd97">

**Comment by andiweli** [comment]
Konntet ihr damit was anfangen?
Mehr Output kommt über die Konsole in dem Fall leider nicht daher 🤷🏻‍♂️

**Comment by andiweli** [comment]
Gibt's evtl Infos ob eine Portweiterleitung notwendig ist?

Hab den Raspberry in einem Mesh das wiederum an einem Glasfasermodem hängt. 

Zugriff intern klappt. 
Zugriff von extern seit Monaten nicht. 

Danke.

**Comment by Garfonso** [comment]
Also eine Portweiterleitung ist nicht notwendig. Dafür ist der cloud adapter ja genau da. 

@GermanBluefox 
Ich habe nochmal gesucht mit allem, was ich mir angucken kann.
Dabei ist mir zum einen aufgefallen, dass lovelace ganz schön viele Dateien anfordert (und irgendwie auch js.map Dateien, die alle zu 404 führen) -> kann das zu einem "soft ban" oder so führen? Also dass der cloud Server davon ausgeht, dass es zu viele Requests sind?

Irgendwas scheint jedenfalls dazu zu führen, dass die websocket Verbindung nicht funktioniert. Im Browser kann ich sehen, dass er versucht sich zu authentifiziere:
```{"type":"auth","access_token":"no_token"}```
darauf kommt dann keine Antwort und nach einer Minute schließt der Browser den socket und versucht es nochmal.

Im Adapter scheint eine leere (??) message anzukommen, weshalb der aussteigt, jedenfalls sehe ich im system log diese Ausgaben:
```
Nov 12 12:25:10 Server node[11837]: Cannot parse message:
Nov 12 12:25:12 Server node[11837]: Cannot parse message:
Nov 12 12:43:35 Server node[11837]: Cannot parse message:
Nov 12 12:44:27 Server node[11837]: Cannot parse message:
Nov 12 12:44:36 Server node[11837]: Cannot parse message:
```

Die kommt ziemlich sicher von [hier](https://github.com/ioBroker/ioBroker.lovelace/blob/39fc27bee297081b8cbf9d5208e901dbe7286847/lib/server.js#L2304).

Das erklärt zumindest, warum der Adapter nicht antwortet, er steigt da mit einem return aus der "onMessage" Funktion aus. 

Aaalso hab ich mal mehr debug hinzugefügt.. und.. naja... 
```
Could not parse message: with type object, got error SyntaxError: Unexpected end of JSON input 
with stack SyntaxError: Unexpected end of JSON input at JSON.parse (<anonymous>) at WebSocket.<anonymous> (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:2306:32) at WebSocket.emit (node:events:519:28) at Receiver.receiverOnMessage (/opt/iobroker/node_modules/ws/lib/websocket.js:1220:20) at Receiver.emit (node:events:519:28) at Receiver.dataMessage (/opt/iobroker/node_modules/ws/lib/receiver.js:569:14) at Receiver.getData (/opt/iobroker/node_modules/ws/lib/receiver.js:496:10) at Receiver.startLoop (/opt/iobroker/node_modules/ws/lib/receiver.js:167:16) at Receiver._write (/opt/iobroker/node_modules/ws/lib/receiver.js:94:10) at writeOrBuffer (node:internal/streams/writable:570:12). 
```
Hm.. object??
Also hab ich mir die Message mal stringifien lassen:
`Stringified message: { "type": "Buffer", "data": [] }`

Bis dahin bin ich gerade mit meinen Recherchen gekommen und weiß nicht so recht weiter... das Objekt scheint zumindest nicht eine Instanz von Buffer zu sein, auch wenn die type-Propertie das nahelegt. Kann es sein, dass da irgendwo unterwegs (subtil, ggf. durch neueres Node?) ein String zu einem Buffer wird und der dann unvollständig weiter gereicht wird?

**Comment by Garfonso** [comment]
Hm.. hab den Browser einfach die ganze Nacht offen gelassen und morgens war Lovelace dann verbunden... *seufz* Also es ist irgendwo was random dabei, dass es funktioniert / nicht funktioniert... aber nach F5 drücken geht es gerade zumindest wieder zuverlässig nicht. Immerhin. ;-)

**Comment by Garfonso** [comment]
Ok, hab jetzt auch mal im cloud-Adapter debug logging eingebaut und die Nachricht `{"type":"auth","access_token":"no_token"}` die Lovelace laut Man-In-The-Middle Proxy im Browser über die websocket Verbindung schon rausgeschickt hat, kommt in den Fällen, wo eine Verbindung nicht zustande kommt, einfach nicht bei lovelace an, sondern es kommt nur

```
13 Nov 2024 09:34:39.718 cloud.0: [Lovelace|17bdffef-0ca9-4aec-a1b1-b1f318219798] connected
13 Nov 2024 09:34:39.718 cloud.0: [Lovelace|17bdffef-0ca9-4aec-a1b1-b1f318219798] store message: undefined
13 Nov 2024 09:34:39.718 cloud.0: [Lovelace|17bdffef-0ca9-4aec-a1b1-b1f318219798] establish connection
13 Nov 2024 09:34:39.718 cloud.0: Incomming data: ["{\"type\":\"connection\"}"]
```
(die Ausgaben sind "neueste oben", die unterste Zeile ist eine debug Ausgabe, die ich reingehackt hab, die einfach das komplette args-Array ausgibt, wo das klar ist, dass die Nachricht an lovelace gehen soll. (also [hier](https://github.com/ioBroker/ioBroker.cloud/blob/808d1b289379abf810e2714ac2ad6df7a5c25fad/lib/socketCloud.js#L212)).
Danach passiert eine Minute lang nichts, bis lovelace im Browser aufgibt und einen neuen Versuch startet.

Kann es da irgendwo eine race-condition geben, bei der die erste Websocket Nachricht von lovelace verloren geht?

**Comment by SKB-CGN** [comment]
Hallo Zusammen,
ich habe das Problem nicht mit lovelace sondern mit meinem Energiefluss-erweitert Adapter.

Über Firefox kommt er die meiste Zeit problemlos rein - mit Chrome bleibt es bei der Ladeanimation hängen.

Die Socket Verbindung wird aufgebaut und der cloud Adapter meldet brav, das ein user sich verbunden hat. Mehr kommt leider nicht.

**Comment by planetofrock** [comment]
The same problem here. Lovelace don't work with iobroker.pro.
Is there nobody can fix it or work on this adapter?

**Comment by 2K-Darkness** [comment]
@GermanBluefox 
Kannst Du hier nicht nochmal schauen?
Lovelace lädt bei mir wie bei andiweli oder Garfonso von extern ins unendliche, wobei es MANCHMAL nach 20 Versuchen klappt...
Ich kann auch zur Fehlersuche beitragen wenn notwendig!

Grüße

**Comment by andiweli** [comment]
Ich bin mittlerweile umgestiegen und habe TailScale als VPN auf meinem Raspberry und iPhone laufen und greife direkt im Browser von unterwegs auf Lovelace zu. Funktioniert tadellos und schnell. Man braucht die ioBroker App auch nicht dazu. Safari, als Webapp speichern.

**Comment by Dette70** [comment]
> Ich bin mittlerweile umgestiegen und habe TailScale als VPN auf meinem Raspberry und iPhone laufen und greife direkt im Browser von unterwegs auf Lovelace zu. Funktioniert tadellos und schnell. Man braucht die ioBroker App auch nicht dazu. Safari, als Webapp speichern.

Ist sicher eine Alternative.
Allerdings ist der Pro Zugriff ja nicht kostenlos und der Lovelace Adapter wirbt mit dem Feature. Daher wäre es schon sinnvoll, wenn das auch wie beschrieben klappt.

Hier noch mein Log Eintrag auf dem Iobroker, beim Zugriffsversuch:

`lovelace.0 | 2025-04-29 10:38:56.200 | debug | Connection closed
-- | -- | -- | --
cloud.0 | 2025-04-29 10:38:56.196 | info | [Lovelace\|f502d6c7-8461-4be9-bc5d-2eb4f5622631] remote client disconnected
lovelace.0 | 2025-04-29 10:37:56.287 | debug | PRO-debug stringified message: ""
lovelace.0 | 2025-04-29 10:37:56.286 | debug | Could  not parse message:  with type string, got error SyntaxError: Unexpected  end of JSON input with stack SyntaxError: Unexpected end of JSON input     at JSON.parse (<anonymous>)     at WebSocket.<anonymous>  (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:2688:32)     at WebSocket.emit (node:events:524:28)     at Receiver.receiverOnMessage  (/opt/iobroker/node_modules/ws/lib/websocket.js:1220:20)     at Receiver.emit (node:events:524:28)     at Receiver.dataMessage  (/opt/iobroker/node_modules/ws/lib/receiver.js:569:14)     at Receiver.getData  (/opt/iobroker/node_modules/ws/lib/receiver.js:496:10)     at Receiver.startLoop  (/opt/iobroker/node_modules/ws/lib/receiver.js:167:16)     at Receiver._write  (/opt/iobroker/node_modules/ws/lib/receiver.js:94:10)     at writeOrBuffer (node:internal/streams/writable:572:12)     at _write (node:internal/streams/writable:501:10)     at Writable.write (node:internal/streams/writable:510:10)     at Socket.socketOnData  (/opt/iobroker/node_modules/ws/lib/websocket.js:1355:35)     at Socket.emit (node:events:524:28)     at addChunk (node:internal/streams/readable:561:12)     at readableAddChunkPushByteMode  (node:internal/streams/readable:512:3)     at Readable.push (node:internal/streams/readable:392:5)     at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
lovelace.0 | 2025-04-29 10:37:56.285 | debug | PRO-debug: ws message is buffer
lovelace.0 | 2025-04-29 10:37:56.284 | debug | PRO-debug: ws message received
lovelace.0 | 2025-04-29 10:37:54.787 | debug | PRO-debug: ws close
lovelace.0 | 2025-04-29 10:37:54.787 | debug | Connection closed`

**Comment by andiweli** [comment]
> > Ich bin mittlerweile umgestiegen und habe TailScale als VPN auf meinem Raspberry und iPhone laufen und greife direkt im Browser von unterwegs auf Lovelace zu. Funktioniert tadellos und schnell. Man braucht die ioBroker App auch nicht dazu. Safari, als Webapp speichern.
> 
> Ist sicher eine Alternative. Allerdings ist der Pro Zugriff ja nicht kostenlos und der Lovelace Adapter wirbt mit dem Feature. Daher wäre es schon sinnvoll, wenn das auch wie beschrieben klappt.

Ja ich hab 2 Jahre Pro bezahlt aber vergebens gekämpft, dass der Bug behoben wird.
Somit wird Pro nicht verlängert und ich löse es selbst direkt über ein VPN.
Der Lovelace Adapter selbst ist genial, da hat Garfonso schon tolle Arbeit geleistet, aber dass da seit 2023 der Fehler nicht gefunden wird mit der App hat mich dann schon gestört...

**Comment by 2K-Darkness** [comment]
Hi!

Hab ich jetzt auch so gemacht. Mit iOS "Kurzbefehle" konnt ich es auch noch ein wenig automatisieren.
Wenn ich das Widget dazu nun anklicke, wird die VPN-Verbindung automatisch geöffnet und der Safari mit Lovelace im Anschluss direkt aufgerufen. Nach 90sek. wird die Verbuindung dann automatisch getrennt. Für den Fall das man es vergisst und der Akku leer geht.

Grüße und Danke

**Comment by Garfonso** [comment]
Bitte nochmal mit 7.x ausprobieren. Claude behauptet, dass jetzt nur noch ca. 1/4 der Daten über die cloud angefordert werden müssen.
