### ISSUE TITLE
Adapterinstanz stürzt beim Start häufig ab und wurde aus diesem Grund gestoppt...

### ISSUE THREAD

**Issue by 5G7K** [ioBroker/ioBroker.lovelace#503]
Nachts abgestürzt:
Eine Adapterinstanz stürzt beim Start häufig ab und wurde aus diesem Grund gestoppt. Die Protokolldatei muss vor dem Neustart der Instanz überprüft werden.

system.host.iobroker:   
lovelace.0: 25.2.2024, 00:16:06 Restart loop detected

```
2024-02-25 00:10:01.412 - error: lovelace.0 (348208) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
--
2024-02-25 00:10:01.422 - error: lovelace.0 (348208) unhandled promise rejection: Cannot set properties of null (setting '0')
2024-02-25 00:10:01.427 - error: lovelace.0 (348208) TypeError: Cannot set properties of null (setting '0')
at hue_attr.getParser (/opt/iobroker/node_modules/iobroker.lovelace/lib/converters/light.js:179:43)
at /opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:799:38
at Array.forEach ()
at WebServer.onStateChange (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:775:22)
at Object.stateChange (/opt/iobroker/node_modules/iobroker.lovelace/main.js:54:35)
at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8462:47
at Array.forEach ()
at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8446:35)
at Immediate. (/opt/iobroker/node_modules/@iobroker/db-states-redis/build/lib/states/statesInRedisClient.js:270:37)
at process.processImmediate (node:internal/timers:476:21)
2024-02-25 00:10:01.428 - error: lovelace.0 (348208) Cannot set properties of null (setting '0')
2024-02-25 00:10:01.435 - warn: lovelace.0 (348208) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-02-25 00:10:02.036 - error: host.iobroker instance system.adapter.lovelace.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
```

**To Reproduce**  
konnte ich heute morgen nicht mehr reproduzieren. Ließ sich wieder starten. Wahrscheinlich hatte irgendein State einen unglücklichen Wert...?

**Versions:**  
 - Adapter version: 4.1.4
 - JS-Controller version: 5.0.19
 - Node version: v18.19.0
 - Operating system: linux

**Comment by Garfonso** [comment]
Danke für den report. 
Es freut mich, dass der Adapter (wieder) läuft. Ja, das ist ein Problem in der 4.1.4. Ich hab es noch nicht geschafft den abschließend zu fixen (so dass alle Funktionen weiter gehen). Falls es weiter auftritt, auf die 4.1.3 oder so zurückgehen. Ich hoffe, dass ich bald eine 4.1.5 rausbringen kann, die das dann behebt und auch wieder in stable gehen wird.

**Comment by 5G7K** [comment]
Hi Garfonso. gestern 4.1.5 installiert. Leider tritt das Problem immer noch auf.

In diesem Fall hat es wohl mit einer Zigbee Lampe zu tun?

```
2024-03-06 23:51:01.214 - error: lovelace.0 (538791) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-03-06 23:51:01.216 - error: lovelace.0 (538791) unhandled promise rejection: Cannot set properties of null (setting '0')
2024-03-06 23:51:01.218 - error: lovelace.0 (538791) TypeError: Cannot set properties of null (setting '0')
at hue_attr.getParser (/opt/iobroker/node_modules/iobroker.lovelace/lib/converters/light.js:211:42)
at /opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:798:38
at Array.forEach ()
at WebServer.onStateChange (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:774:22)
at Object.stateChange (/opt/iobroker/node_modules/iobroker.lovelace/main.js:54:35)
at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8462:47
at Array.forEach ()
at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8446:35)
at Immediate. (/opt/iobroker/node_modules/@iobroker/db-states-redis/build/lib/states/statesInRedisClient.js:270:37)
at process.processImmediate (node:internal/timers:476:21)
2024-03-06 23:51:01.218 - error: lovelace.0 (538791) Cannot set properties of null (setting '0')
2024-03-06 23:51:01.234 - warn: lovelace.0 (538791) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-03-06 23:51:01.818 - error: host.iobroker instance system.adapter.lovelace.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-03-06 23:51:01.818 - info: host.iobroker Restart adapter system.adapter.lovelace.0 because enabled
2024-03-06 23:51:02.913 - info: host.iobroker instance system.adapter.lovelace.0 started with pid 538864
2024-03-06 23:52:32.462 - info: javascript.0 (329) script.js.Zigbee.Warnleuchte_Ankleide: Lampe Ankleide OFF
2024-03-06 23:52:32.474 - warn: deconz.0 (2045) Failed action "hue" on light 9! Description: parameter, hue, is not modifiable. Device is set to off.
2024-03-06 23:52:32.475 - warn: deconz.0 (2045) {"address":"/lights/9/state/hue","description":"parameter, hue, is not modifiable. Device is set to off.","type":201}
2024-03-06 23:52:32.518 - warn: deconz.0 (2045) Failed action "sat" on light 9! Description: parameter, sat, is not modifiable. Device is set to off.
2024-03-06 23:52:32.518 - warn: deconz.0 (2045) {"address":"/lights/9/state/sat","description":"parameter, sat, is not modifiable. Device is set to off.","type":201}
2024-03-06 23:52:32.750 - error: lovelace.0 (538864) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-03-06 23:52:32.756 - error: lovelace.0 (538864) unhandled promise rejection: Cannot set properties of null (setting '1')
2024-03-06 23:52:32.761 - error: lovelace.0 (538864) TypeError: Cannot set properties of null (setting '1')
at sat_attr.getParser (/opt/iobroker/node_modules/iobroker.lovelace/lib/converters/light.js:234:46)
at /opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:798:38
at Array.forEach ()
at WebServer.onStateChange (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:774:22)
at Object.stateChange (/opt/iobroker/node_modules/iobroker.lovelace/main.js:54:35)
at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8462:47
at Array.forEach ()
at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8446:35)
at Immediate. (/opt/iobroker/node_modules/@iobroker/db-states-redis/build/lib/states/statesInRedisClient.js:270:37)
at process.processImmediate (node:internal/timers:476:21)
2024-03-06 23:52:32.762 - error: lovelace.0 (538864) Cannot set properties of null (setting '1')
2024-03-06 23:52:32.770 - warn: lovelace.0 (538864) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-03-06 23:52:33.379 - error: host.iobroker instance system.adapter.lovelace.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-03-06 23:52:33.380 - info: host.iobroker Restart adapter system.adapter.lovelace.0 because enabled
2024-03-06 23:52:33.380 - warn: host.iobroker Do not restart adapter system.adapter.lovelace.0 because restart loop detected
```

**Comment by 5G7K** [comment]
Ja war 4.1.5
```
2024-03-06 22:36:56.951 - info: host.iobroker iobroker upgrade lovelace@4.1.5 --debug
2024-03-06 22:36:57.956 - info: host.iobroker iobroker Update lovelace from @4.1.2 to @4.1.5
2024-03-06 22:36:58.251 - info: host.iobroker iobroker NPM version: 10.2.3
2024-03-06 22:36:58.251 - info: host.iobroker iobroker Installing iobroker.lovelace@4.1.5... (System call)
```

Seit gestern Abend 4.1.6
Bisher keine Probleme. Ich behalte das im Blick und berichte falls es noch Probleme gibt.

Vielen Dank für den Support!

**Comment by 5G7K** [comment]
Leider mit 4.1.6 wieder abgestürzt.
Das liegt denke ich an einer Zigbee-Lampe, die über Deconz gesteuert wird?
Wenn das Licht geschaltet wird bzw. Werte gesetzt werden, dann stürzt LL ab. 
Diese Lampe ist auch in LL eingebunden.
type: light
entity: light.Ankleide_Licht_Hue

```
2024-03-07 22:12:10.328 - info: host.iobroker iobroker upgrade lovelace@4.1.6 --debug
2024-03-07 22:12:11.220 - info: host.iobroker iobroker Update lovelace from @4.1.2 to @4.1.6
2024-03-07 22:12:11.508 - info: host.iobroker iobroker NPM version: 10.2.3
2024-03-07 22:12:11.508 - info: host.iobroker iobroker Installing iobroker.lovelace@4.1.6... (System call)
2024-03-07 22:12:16.450 - info: host.iobroker iobroker changed 1 package in 5s
2024-03-07 22:12:16.451 - info: host.iobroker iobroker 161 packages are looking for funding run `npm fund` for details
2024-03-07 22:12:16.539 - info: host.iobroker iobroker Update "system.adapter.lovelace.0"
2024-03-07 22:12:16.582 - info: host.iobroker stopInstance system.adapter.lovelace.0 (force=false, process=true)
```

```
2024-03-08 22:35:57.233 - warn: deconz.0 (2045) Failed action "hue" on light 9! Description: parameter, hue, is not modifiable. Device is set to off.
--
2024-03-08 22:35:57.243 - warn: deconz.0 (2045) {"address":"/lights/9/state/hue","description":"parameter, hue, is not modifiable. Device is set to off.","type":201}
2024-03-08 22:35:57.290 - warn: deconz.0 (2045) Failed action "sat" on light 9! Description: parameter, sat, is not modifiable. Device is set to off.
2024-03-08 22:35:57.290 - warn: deconz.0 (2045) {"address":"/lights/9/state/sat","description":"parameter, sat, is not modifiable. Device is set to off.","type":201}
2024-03-08 22:35:57.339 - error: lovelace.0 (559357) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-03-08 22:35:57.341 - error: lovelace.0 (559357) unhandled promise rejection: Cannot set properties of null (setting '1')
2024-03-08 22:35:57.343 - error: lovelace.0 (559357) TypeError: Cannot set properties of null (setting '1')
at sat_attr.getParser (/opt/iobroker/node_modules/iobroker.lovelace/lib/converters/light.js:237:46)
at /opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:798:38
at Array.forEach ()
at WebServer.onStateChange (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:774:22)
at Object.stateChange (/opt/iobroker/node_modules/iobroker.lovelace/main.js:54:35)
at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8462:47
at Array.forEach ()
at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8446:35)
at Immediate. (/opt/iobroker/node_modules/@iobroker/db-states-redis/build/lib/states/statesInRedisClient.js:270:37)
at process.processImmediate (node:internal/timers:476:21)
2024-03-08 22:35:57.343 - error: lovelace.0 (559357) Cannot set properties of null (setting '1')
2024-03-08 22:35:57.346 - warn: lovelace.0 (559357) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-03-08 22:35:57.347 - info: notification-manager.0 (492689) New notification on "iobroker" detected
2024-03-08 22:35:57.949 - error: host.iobroker instance system.adapter.lovelace.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-03-08 22:35:57.949 - info: host.iobroker Restart adapter system.adapter.lovelace.0 because enabled
2024-03-08 22:35:59.027 - info: host.iobroker instance system.adapter.lovelace.0 started with pid 571483
```

```
2024-03-08 22:41:01.187 - error: lovelace.0 (571483) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
--
2024-03-08 22:41:01.190 - error: lovelace.0 (571483) unhandled promise rejection: Cannot set properties of null (setting '1')
2024-03-08 22:41:01.192 - error: lovelace.0 (571483) TypeError: Cannot set properties of null (setting '1')
at sat_attr.getParser (/opt/iobroker/node_modules/iobroker.lovelace/lib/converters/light.js:237:46)
at /opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:798:38
at Array.forEach ()
at WebServer.onStateChange (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:774:22)
at Object.stateChange (/opt/iobroker/node_modules/iobroker.lovelace/main.js:54:35)
at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8462:47
at Array.forEach ()
at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8446:35)
at Immediate. (/opt/iobroker/node_modules/@iobroker/db-states-redis/build/lib/states/statesInRedisClient.js:270:37)
at process.processImmediate (node:internal/timers:476:21)
2024-03-08 22:41:01.192 - error: lovelace.0 (571483) Cannot set properties of null (setting '1')
2024-03-08 22:41:01.196 - warn: lovelace.0 (571483) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-03-08 22:41:01.814 - error: host.iobroker instance system.adapter.lovelace.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-03-08 22:41:01.815 - info: host.iobroker Restart adapter system.adapter.lovelace.0 because enabled
2024-03-08 22:41:02.948 - info: host.iobroker instance system.adapter.lovelace.0 started with pid 571548
2024-03-08 22:41:39.319 - warn: deconz.0 (2045) Failed action "hue" on light 9! Description: parameter, hue, is not modifiable. Device is set to off.
2024-03-08 22:41:39.319 - warn: deconz.0 (2045) {"address":"/lights/9/state/hue","description":"parameter, hue, is not modifiable. Device is set to off.","type":201}
2024-03-08 22:41:39.362 - warn: deconz.0 (2045) Failed action "sat" on light 9! Description: parameter, sat, is not modifiable. Device is set to off.
2024-03-08 22:41:39.362 - warn: deconz.0 (2045) {"address":"/lights/9/state/sat","description":"parameter, sat, is not modifiable. Device is set to off.","type":201}
2024-03-08 22:41:39.492 - error: lovelace.0 (571548) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-03-08 22:41:39.494 - error: lovelace.0 (571548) unhandled promise rejection: Cannot set properties of null (setting '1')
2024-03-08 22:41:39.496 - error: lovelace.0 (571548) TypeError: Cannot set properties of null (setting '1')
at sat_attr.getParser (/opt/iobroker/node_modules/iobroker.lovelace/lib/converters/light.js:237:46)
at /opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:798:38
at Array.forEach ()
at WebServer.onStateChange (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:774:22)
at Object.stateChange (/opt/iobroker/node_modules/iobroker.lovelace/main.js:54:35)
at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8462:47
at Array.forEach ()
at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8446:35)
at Immediate. (/opt/iobroker/node_modules/@iobroker/db-states-redis/build/lib/states/statesInRedisClient.js:270:37)
at process.processImmediate (node:internal/timers:476:21)
2024-03-08 22:41:39.496 - error: lovelace.0 (571548) Cannot set properties of null (setting '1')
2024-03-08 22:41:39.499 - warn: lovelace.0 (571548) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-03-08 22:41:40.080 - error: host.iobroker instance system.adapter.lovelace.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-03-08 22:41:40.080 - info: host.iobroker Restart adapter system.adapter.lovelace.0 because enabled
2024-03-08 22:41:40.080 - warn: host.iobroker Do not restart adapter system.adapter.lovelace.0 because restart loop detected
```

Mit 4.1.2 funktioniert alles ohne Probleme. 4.1.3 kann ich irgendwie nicht installieren. Bricht ab.
Was die deconz Warnungen bedeuten, habe ich noch nicht herausgefunden. 

Hast du noch eine Idee was du ändern könntest bzw. was ich ausprobieren soll?
Danke!

**Comment by 5G7K** [comment]
Seit einigen Tagen 4.1.8 im Einsatz. Hiermit keine Abstürze mehr.
Vielen Dank!
